{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNAK+z2yQcKsQRdfFVPBFEO",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/gowthamkalyan0/gowtham/blob/main/3.%20ID3%20decision%20tree.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 12,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Qb1TIf7FVLra",
        "outputId": "c4490bdb-988f-440c-e66b-275ba9a56b46"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Attribute 3 : Weak? \n",
            "--> True:\n",
            " Attribute None : None? \n",
            " --> True:\n",
            " --> False:\n",
            "--> False:\n",
            " Attribute None : None? \n",
            " --> True:\n",
            " --> False:\n",
            "\n",
            "Classification result for ['Sunny', 'Cool', 'High', 'Strong']: None\n"
          ]
        }
      ],
      "source": [
        "import math # Import math for log2\n",
        "\n",
        "class Node:\n",
        "    def __init__(self, attribute=None, value=None, results=None, true_branch=None,\n",
        "                 false_branch=None):\n",
        "        self.attribute, self.value, self.results, self.true_branch, self.false_branch = \\\n",
        "            attribute, value, results, true_branch, false_branch\n",
        "\n",
        "def class_counts(rows):\n",
        "    # Counts the number of each result (the last column) in a set of rows\n",
        "    counts = {}\n",
        "    for row in rows:\n",
        "        label = row[-1]\n",
        "        counts[label] = counts.get(label, 0) + 1\n",
        "    return counts\n",
        "\n",
        "def entropy(rows):\n",
        "    counts = class_counts(rows)\n",
        "    if not counts: # Handle empty rows list\n",
        "        return 0.0\n",
        "    total_rows = len(rows)\n",
        "    ent = 0.0\n",
        "    for count in counts.values():\n",
        "        p = count / total_rows\n",
        "        if p > 0: # Avoid log2(0)\n",
        "            ent -= p * math.log2(p) # Use math.log2\n",
        "    return ent\n",
        "\n",
        "# Helper function to calculate information gain for a specific binary split\n",
        "def information_gain_for_split(parent_rows, true_rows, false_rows):\n",
        "    # Entropy of the parent node\n",
        "    total_entropy = entropy(parent_rows)\n",
        "\n",
        "    # Calculate weighted entropy of children\n",
        "    len_parent = len(parent_rows)\n",
        "    len_true = len(true_rows)\n",
        "    len_false = len(false_rows)\n",
        "\n",
        "    weighted_entropy = 0.0\n",
        "    if len_true > 0:\n",
        "        weighted_entropy += (len_true / len_parent * entropy(true_rows))\n",
        "    if len_false > 0:\n",
        "        weighted_entropy += (len_false / len_parent * entropy(false_rows))\n",
        "\n",
        "    return total_entropy - weighted_entropy\n",
        "\n",
        "def build_tree(rows):\n",
        "    if not rows:\n",
        "        return Node()\n",
        "    if len(set(row[-1] for row in rows)) == 1:\n",
        "        return Node(results=rows[0][-1])\n",
        "\n",
        "    num_attributes = len(rows[0]) - 1\n",
        "    best_gain = 0.0\n",
        "    best_attribute = None\n",
        "    best_split_value = None\n",
        "\n",
        "    for col in range(num_attributes):\n",
        "        unique_values = set(row[col] for row in rows)\n",
        "        for val in unique_values:\n",
        "            # Split rows based on current attribute 'col' and value 'val'\n",
        "            sub_rows_true = [row for row in rows if row[col] == val]\n",
        "            sub_rows_false = [row for row in rows if row[col] != val]\n",
        "\n",
        "            # Avoid division by zero if one branch is empty in information_gain_for_split,\n",
        "            # or if it would result in a child node having 0 rows (handled by entropy)\n",
        "            # The entropy function now handles empty lists so this check is mostly for conceptual clarity\n",
        "            if not sub_rows_true or not sub_rows_false:\n",
        "                continue\n",
        "\n",
        "            current_gain = information_gain_for_split(rows, sub_rows_true, sub_rows_false)\n",
        "\n",
        "            if current_gain > best_gain:\n",
        "                best_gain = current_gain\n",
        "                best_attribute = col\n",
        "                best_split_value = val\n",
        "\n",
        "    # If no gain found (e.g., all remaining attributes have 0 gain, or cannot split meaningfully)\n",
        "    # create a leaf node with the majority class.\n",
        "    if best_gain == 0:\n",
        "        counts = class_counts(rows)\n",
        "        if counts: # Ensure counts is not empty\n",
        "            majority_class = max(counts, key=counts.get)\n",
        "            return Node(results=majority_class)\n",
        "        else: # Should not happen if rows was not empty initially\n",
        "            return Node()\n",
        "\n",
        "\n",
        "    # Now split based on the best found attribute and value\n",
        "    true_rows = [row for row in rows if row[best_attribute] == best_split_value]\n",
        "    false_rows = [row for row in rows if row[best_attribute] != best_split_value]\n",
        "\n",
        "    true_branch = build_tree(true_rows)\n",
        "    false_branch = build_tree(false_rows)\n",
        "\n",
        "    return Node(attribute=best_attribute, value=best_split_value, true_branch=true_branch,\n",
        "                false_branch=false_branch)\n",
        "\n",
        "# Example dataset (you can modify this as needed)\n",
        "dataset = [\n",
        "    ['Sunny', 'Hot', 'High', 'Weak', 'No'],\n",
        "    ['Sunny', 'Hot', 'High', 'Strong', 'No'],\n",
        "    ['Overcast', 'Hot', 'High', 'Weak', 'Yes'],\n",
        "    ['Rain', 'Mild', 'High', 'Weak', 'Yes'],\n",
        "    ['Rain', 'Cool', 'Normal', 'Weak', 'Yes'],\n",
        "    ['Rain', 'Cool', 'Normal', 'Strong', 'No'],\n",
        "    ['Overcast', 'Cool', 'Normal', 'Strong', 'Yes'],\n",
        "    ['Sunny', 'Mild', 'High', 'Weak', 'No'],\n",
        "    ['Sunny', 'Cool', 'Normal', 'Weak', 'Yes'],\n",
        "    ['Rain', 'Mild', 'Normal', 'Weak', 'Yes']\n",
        "]\n",
        "# Build the decision tree\n",
        "tree = build_tree(dataset)\n",
        "# Print the decision tree\n",
        "def print_tree(node, indent=\"\"):\n",
        "    if node is None:\n",
        "        return\n",
        "    if node.results is not None:\n",
        "        print(indent + str(node.results))\n",
        "    else:\n",
        "        print(indent + f'Attribute {node.attribute} (value: {node.value})? ')\n",
        "        print(indent + '--> True (is value):')\n",
        "        print_tree(node.true_branch, indent + '  ') # Increased indent for clarity\n",
        "        print(indent + '--> False (not value):')\n",
        "        print_tree(node.false_branch, indent + '  ') # Increased indent for clarity\n",
        "\n",
        "print_tree(tree)\n",
        "# Classify a new sample\n",
        "new_sample = ['Sunny', 'Cool', 'High', 'Strong']\n",
        "current_node = tree\n",
        "while current_node.results is None and current_node.attribute is not None:\n",
        "    if new_sample[current_node.attribute] == current_node.value:\n",
        "        current_node = current_node.true_branch\n",
        "    else:\n",
        "        current_node = current_node.false_branch\n",
        "print(f\"\\nClassification result for {new_sample}: {current_node.results}\")"
      ]
    }
  ]
}